### ISSUE TITLE
[Bug][Staging][Medium] Setup Your Profile Field Validation Wording

### ISSUE THREAD

**Issue by iqbal-wira** [glovory/werk-b2c-webapp#67]
**User Stories :**
- https://www.notion.so/glovory/Talent-Profile-Registration-a9a990c0ef97417f9bde27203d54e957

**Test Data :**

**Step To Reproduce :**
1. Register with google account
2. Skip this step

**Current Condition :**
1. Full name less than 3 character : There's no validation
2. Account name empty : Account Name is required and can't be empty.
3. Account name valid : There's no valid information

**Expected Condition :**
1. Full name less than 3 character : The name must be at least 3 characters or more.
2. Account name empty : Account name is required and can't be empty.
3. Account name valid : Valid information "Account name is available for you to use." and icon Checked

**Reference :**
- https://preview.uxpin.com/4229e36f7d1df0d78bc38bbcf0a5a7d3900004b9#/pages/159811300/simulate/sitemap

**Evidence :**
![Screenshot 2023-01-03 103046](https://user-images.githubusercontent.com/106940323/210296851-9e064ec4-e012-499c-b6a2-e975fa6a9699.jpg)
![Screenshot 2023-01-03 103106](https://user-images.githubusercontent.com/106940323/210296853-8de7ce1b-3954-434d-87a1-0d6c119b8b82.jpg)
![Screenshot 2023-01-03 103144](https://user-images.githubusercontent.com/106940323/210296857-538a508b-0239-42ec-9541-b5b04b11f787.jpg)

**Comment by M-Husein** [comment]
mas @iqbal-wira , mas @idzharin .
Ini udah saya fix ya, minta tolong di cek lg. Thanks.

**Comment by iqbal-wira** [comment]
hi mas @M-Husein 
in the account name field should be displayed validation for less than 3 characters
![Screenshot 2023-01-04 084439](https://user-images.githubusercontent.com/106940323/210469455-e361f6ff-04f7-4a0d-a063-eb291a51915e.jpg)

**Comment by iqbal-wira** [comment]
This issue confirmed as fixed.
Thanks
Evidence :
![Image](https://user-images.githubusercontent.com/106940323/210717780-f697a544-1339-4c0f-8220-0f99dc419e6a.jpg)
![Image](https://user-images.githubusercontent.com/106940323/210717796-11396587-df12-498f-b72f-1ee627bf9e89.jpg)
![Image](https://user-images.githubusercontent.com/106940323/210717814-d17b16f3-0895-4d4f-a1d2-093a8aeef6c2.jpg)
