### ISSUE TITLE
[UI][Staging][Minor] Sequel for Province And City Dropdown Selection

### ISSUE THREAD

**Issue by iqbal-wira** [glovory/werk-b2c-webapp#68]
**User Stories:**
https://www.notion.so/glovory/Talent-Profile-Registration-a9a990c0ef97417f9bde27203d54e957

**Test Data :**

**Step To Reproduce :**
1. Register with google account
2. Skip this step

**Current Condition :**
- Dropdown selection for City displayed even user didn't select Province/State

**Expected Condition :**
- Dropdown selection for city displayed after user select P{rovince/State

**Reference :**
- https://preview.uxpin.com/4229e36f7d1df0d78bc38bbcf0a5a7d3900004b9#/pages/159811300/simulate/sitemap

**Evidence :**
![Screenshot 2023-01-03 103341](https://user-images.githubusercontent.com/106940323/210297099-eec894a0-1ca3-4f1e-aa42-beaa2b9e2c6d.jpg)

**Comment by M-Husein** [comment]
Halo mas @iqbal-wira mas @idzharin 
Issue ini sudah saya fix, minta tolong di cek lg. Thanks mas.

**Comment by iqbal-wira** [comment]
Hi mas @M-Husein 
This issue confirmed as fixed.
Thanks
Evidence 

![Image](https://user-images.githubusercontent.com/106940323/210319440-8221d9b6-6756-455b-9e6b-fafb8cc55a70.jpg)
https://user-images.githubusercontent.com/106940323/210319415-b07817ba-59cb-475a-9e7f-2f14ccb0f42a.webm
