### ISSUE TITLE
[Bug][Staging][Medium] There's No Options On City Selector Edit Profile

### ISSUE THREAD

**Issue by iqbal-wira** [glovory/werk-b2c-webapp#85]
**User Stories :**
https://www.notion.so/glovory/Talent-Profile-Web-App-User-Profile-0b74a5ae6e4a49048acfb1235026f2ff

**Test Data :**

**Step To Reproduce :**
1. Click Edit Profile
2. Click City Dropdown

**Current Condition :**
- Displayed "No Options"

**Expected Condition :**
- The Dropdown should be displayed appropriate City data

**Evidence :**
![image_2023-01-06_15-57-41](https://user-images.githubusercontent.com/106940323/210967796-4545731f-4f65-4d4f-864b-3a11a5f5024e.png)
[screen-capture (4).webm](https://user-images.githubusercontent.com/106940323/210967712-9c0c51e0-751b-4133-94d1-305d69b7438c.webm)

**Comment by M-Husein** [comment]
Hi, mas @iqbal-wira cc mas @idzharin 
I have fixed this issue. Please re-test. Thanks.

**Comment by iqbal-wira** [comment]
This issue confirmed as Fixed
Thanks
Evidence :
https://user-images.githubusercontent.com/106940323/211227820-37612c4c-4b7a-4795-a538-e039cdbd4da4.webm
![Image](https://user-images.githubusercontent.com/106940323/211227825-6cfd80c3-9eb4-45db-9a80-3e625a907f4c.jpg)
